# Ansible playbook to configure database server
#
# Colin Hansen
# Bryan Steitz
# Pan Wang
#
# Last Updated: October 27, 2017

  - name: "Replicating database"
    hosts: Db_server
    remote_user: ubuntu
    gather_facts: no
    
    tasks:
      - name: "Create HAProxy user for check"
        mysql_user: name=haproxy_check host='%' state=present
        become: true

      - name: "Create HAProxy user for queries"
        mysql_user: name=haproxy_root password=admin priv=*.*:ALL host='%' state=present
        become: true
      
      - name: "Set server-id"
        lineinfile:
          dest: /etc/mysql/mysql.conf.d/mysqld.cnf
          regexp: '^(.*)server-id(.*)$'
          line: 'server-id              = 1'
          backrefs: true
        become: true

      - name: "Set log_bin"
        lineinfile:
          dest: /etc/mysql/mysql.conf.d/mysqld.cnf
          regexp: '^(.*)log_bin(.*)$'
          line: 'log_bin                        = /var/log/mysql/mysql-bin.log'
          backrefs: true
        become: true

      - name: "Add movie db"
        shell: awk 'NR==87{print "binlog_do_db            = moviedb"}1' /etc/mysql/mysql.conf.d/mysqld.cnf | sudo tee /etc/mysql/mysql.conf.d/mysqld.cnf

      - name: "Add bookstore db"
        shell: awk 'NR==88{print "binlog_do_db            = bookstore"}1' /etc/mysql/mysql.conf.d/mysqld.cnf | sudo tee /etc/mysql/mysql.conf.d/mysqld.cnf

      - name: "Grant slave access"
        mysql_user: name=slave_user host='%' password=admin priv="*.*:REPLICATION SLAVE" state=present
        become: true

      - name: "Dump bookstore"
        mysql_db:
          state: dump
          name: bookstore
          target: /tmp/bookstore_dump.sql
        become: true

      - name: "Move bookstore dump to chameleon"
        command: scp -i cham_key.pem -o StrictHostKeyChecking=no /tmp/bookstore_dump.sql cc@{{ item }}:/tmp/bookstore_dump.sql
        with_items: 
            - "{{ groups['chameleon_db'][0] }}"
      
      - name: "Dump moviedb"
        mysql_db:
          state: dump
          name: moviedb
          target: /tmp/moviedb_dump.sql
        become: true

      - name: "Move bookstore dump to chameleon"
        command: scp -i cham_key.pem -o StrictHostKeyChecking=no /tmp/moviedb_dump.sql cc@{{ item }}:/tmp/moviedb_dump.sql
        with_items: 
            - "{{ groups['chameleon_db'][0] }}"

      - name: "Restart MySQL"
        command: service mysql restart
        become: true

...
