# Ansible playbook to configure database server
#
# Colin Hansen
# Bryan Steitz
# Pan Wang
#
# Last Updated: October 5, 2017

  - name: "Replicating database"
    hosts: Db_server
    remote_user: ubuntu
    gather_facts: no
    
    tasks:
      - name: "Set server-id"
        lineinfile:
          dest: /etc/mysql/mysql.conf.d/mysqld.cnf
          regexp: '^(.*)server_id(.*)$'
          line: 'server-id              = 1'
          backrefs: true
        become: true

      - name: "Set log_bin"
        lineinfile:
          dest: /etc/mysql/mysql.conf.d/mysqld.cnf
          regexp: '^(.*)log_bin(.*)$'
          line: 'log_bin                        = /var/log/mysql/mysql-bin.log'
          backrefs: true
        become: true

      - name: "Add movie db"
        shell: awk 'NR==87{print "binlog_do_db            = moviedb"}1' /etc/mysql/mysql.conf.d/mysqld.cnf | sudo tee /etc/mysql/mysql.conf.d/mysqld.cnf

      - name: "Add bookstore db"
        shell: awk 'NR==88{print "binlog_do_db            = bookstore"}1' /etc/mysql/mysql.conf.d/mysqld.cnf | sudo tee /etc/mysql/mysql.conf.d/mysqld.cnf

      - name: "Grant slave access"
        mysql_user: name=slave_user password=password priv=*.*:REPLICATION SLAVE

      - name: "Restart MySQL"
        command: service mysql restart
        become: true

      
...
