# Ansible playbook to configure local VM
#
# Colin Hansen
# Bryan Steitz
# Pan Wang
#
# Last Updated: September 27, 2017

    - name: "Install python"
      apt: name=python state=latest
      become: true

    - name: "Update OS"
      command: apt-get update
      become: true

    - name: "Install Apache2"
      command: apt-get install -y apache2
      become: true

    - name: "Install php"
      command: apt-get install -y php libapache2-mod-php php-mcrypt php-mysql
      become: true

    - name: "Install git"
      command: apt-get install -y git
      become: true

    - name: "Clone git repo in var/www/ folder"
      command: git clone https://github.com/doc-vu/phpMySQLapp
      become: true
      args:
        chdir: "/var/www/html/"
...
