# Ansible playbook to configure webserver
#
# Colin Hansen
# Bryan Steitz
# Pan Wang
#
# Last Updated: November 12, 2017


#    - name: "Update bookDatabase.php with DB IP"
#      lineinfile:
#        dest: /var/www/html/phpMySQLapp/books/includes/bookDatabase.php
#        regexp: '^(.*)servername =(.*)$'
#        line: '$servername = "{{ item }}";'
#        backrefs: true
#      become: true
#      with_items: 
#          - "{{ groups['Db_server'][0] }}"
#    
#    - name: "Update movieDatabase.php with DB IP"
#      lineinfile:
#        dest: /var/www/html/phpMySQLapp/movies/includes/movieDatabase.php
#        regexp: '^(.*)servername =(.*)$'
#        line: '$servername = "{{ item }}";'
#        backrefs: true
#      become: true
#      with_items: 
#          - "{{ groups['Db_server'][0] }}"
#
#    - name: "Update dir.conf"
#      lineinfile:
#        dest: /etc/apache2/mods-enabled/dir.conf
#        regexp: '^(.*)DirectoryIndex(.*)$'
#        line: ' DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
#        backrefs: true
#      become: true
#
#    - name: "Restart Apache"
#      command: service apache2 restart
#      become: true

    ##########################
    # Docker setup
    ##########################
    
    - name: "Install docker dependencies"
      command: apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      become: true

    - name: "Install docker-py"
      command: pip install docker-py
      become: true

    - name: "Add docker GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      become: true 

    - name: "Setup Repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      become: true

    - name: "Update apt"
      command: apt-get update
      become: true

    - name: "Install docker-ce"
      command: apt-get install -y docker-ce
      become: true


... 
